[template]
name = "rust"

[env.other]
type = "string"
prompt = "What do you really want?"

[env.crate_type]
type = "choices"
prompt = "Do you want a library or binary crate?"
choices = ["lib", "bin"]
default = "bin"
